name: security_report
description: This template should be used when you need help to write your security reports of the code
assignees: Killjoybr
labels: Security
body:
- type: markdown
  attributes:
    value: "# Testing issue templates :) This was actually an issue form!! 0_0 it's amazing  This was never an issue form, apparently issue forms are to collect user input (basically they're the same but different purposes)"
- type: input
  id: Report_text
  attributes:
    label: Report
    description: "Describe the vulnerabilites found and how you suggest the mitigation of them"
    placeholder: "Found Time based SQLInjection vulnerabilities on DD/MM/YYYY. Suggest ...."
  validations:
    required: true
