name: security_report
description: This template should be used when you need help to write your security reports of the code
assignees: Killjoybr
labels: Security
body:
- type: markdown
  attributes:
    value: "# Testing issue templates :) This was actually a issue form!! 0_0 it's amazing"
- type: input
  id: Report_text
  attributes:
    label: Report
    description: "Describe the vulnerabilites found and how you suggest the mitigation of them"
    placeholder: "Found Time based SQLInjection vulnerabilities on DD/MM/YYYY. Suggest ...."
  validations:
    required: true
