___
name: security_report
about: "This template should be used when you need help to write your security reports of the code"
assignees: Killjoybr
labels: Security
___
body:
- type: markdown
  attributes:
    value: # Testing issue templates :)
